#Libraries required for preparation, analysis, and presentation of the data

suppressPackageStartupMessages(library(dplyr))
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(car)
library(plyr)
library(psych)
library(betareg)
library(emmeans)
library(lmtest)
library(multcompView)
library(multcomp)
library(corrplot)
library(factoextra)
library(Rmisc)
library(ggbeeswarm)
library(MASS)